function widget(definition) {
  return Object.freeze({
    ...definition,
    title: Object.freeze(definition.title),
    description: Object.freeze(definition.description),
    metricIds: Object.freeze(definition.metricIds),
    markets: Object.freeze(definition.markets),
  });
}

export const DASHBOARD_WIDGET_DEFINITIONS = Object.freeze([
  widget({
    id: "us-equity-overview",
    title: { zh: "美股大盘", en: "U.S. equity overview" },
    description: { zh: "美股指数代理与黄金代理概况", en: "U.S. index and gold proxy overview" },
    metricIds: [
      "equity.us.qqq.price",
      "equity.us.spy.price",
      "equity.us.dia.price",
      "equity.us.sox.value",
      "commodity.gold.proxy",
    ],
    size: "full",
    defaultPosition: 0,
    markets: ["us", "equity"],
    componentId: "metric-list",
  }),
  widget({
    id: "macro-liquidity-overview",
    title: { zh: "宏观流动性", en: "Macro liquidity" },
    description: { zh: "利率、美元、波动信用与净流动性概况", en: "Rates, dollar, volatility, credit, and net liquidity" },
    metricIds: [
      "macro.riskPosture.score",
      "macro.US10Y.value",
      "macro.US10Y.realYield",
      "macro.DXY.value",
      "macro.VIX.value",
      "macro.HYOAS.value",
      "macro.netLiquidity.usd",
    ],
    size: "full",
    defaultPosition: 1,
    markets: ["macro", "us"],
    componentId: "metric-list",
  }),
  widget({
    id: "market-breadth",
    title: { zh: "加密市场规模", en: "Crypto market scale" },
    description: { zh: "总市值与比特币市值的公开快照", en: "Public snapshots for total and bitcoin market cap" },
    metricIds: ["crypto.totalMarketCap", "btc.marketCap"],
    size: "wide",
    defaultPosition: 2,
    markets: ["crypto"],
    componentId: "metric-list",
  }),
  widget({
    id: "stablecoin-liquidity",
    title: { zh: "稳定币流动性", en: "Stablecoin liquidity" },
    description: { zh: "主要稳定币、USDT 与 USDC 供应规模", en: "Major stablecoin, USDT, and USDC supply" },
    metricIds: ["stablecoin.major.marketCap", "stablecoin.usdt.marketCap", "stablecoin.usdc.marketCap"],
    size: "wide",
    defaultPosition: 3,
    markets: ["crypto"],
    componentId: "metric-list",
  }),
  widget({
    id: "etf-flows",
    title: { zh: "现货 ETF 资金流", en: "Spot ETF flows" },
    description: { zh: "BTC、ETH 与 SOL 日度净流量", en: "Daily BTC, ETH, and SOL net flows" },
    metricIds: ["crypto.etf.BTC.net_flow_usd", "crypto.etf.ETH.net_flow_usd", "crypto.etf.SOL.net_flow_usd"],
    size: "wide",
    defaultPosition: 4,
    markets: ["crypto", "us"],
    componentId: "metric-list",
  }),
  widget({
    id: "strategy-treasury",
    title: { zh: "Strategy 财库", en: "Strategy treasury" },
    description: { zh: "比特币持仓与官方披露平均成本", en: "Bitcoin holdings and officially disclosed average cost" },
    metricIds: ["treasury.mstr.btc_holdings", "treasury.mstr.btc_average_cost_usd"],
    size: "standard",
    defaultPosition: 5,
    markets: ["crypto", "us"],
    componentId: "metric-list",
  }),
  widget({
    id: "bitmine-treasury",
    title: { zh: "BitMine 财库", en: "BitMine treasury" },
    description: { zh: "以太坊持仓与 SEC 成本基础", en: "Ether holdings and SEC cost basis" },
    metricIds: ["treasury.bmnr.eth_holdings", "treasury.bmnr.eth_average_cost_usd"],
    size: "standard",
    defaultPosition: 6,
    markets: ["crypto", "us"],
    componentId: "metric-list",
  }),
  widget({
    id: "japan-rates",
    title: { zh: "日本长期利率", en: "Japan long rates" },
    description: { zh: "日本财务省十年期国债收益率", en: "Japan MOF 10-year government bond yield" },
    metricIds: ["macro.JGB10Y.value"],
    size: "standard",
    defaultPosition: 7,
    markets: ["japan", "macro"],
    componentId: "metric-list",
  }),
]);

export const DASHBOARD_WIDGET_DEFINITION_BY_ID = Object.freeze(Object.fromEntries(
  DASHBOARD_WIDGET_DEFINITIONS.map((definition) => [definition.id, definition]),
));
